/**
 * Writes `docs/stress-patch.txt` from the generator.
 *
 * `npm run stress`. The prose and the figures above the code come from the same run that produced the
 * code, so the file cannot say one thing and carry another — which it could, and twice did, while the
 * code was pasted in by hand and the numbers were typed from a previous version.
 */

import { writeFileSync } from 'node:fs'
import { LAYER_THRESHOLD, MAX_LOAD } from '../audio/load'
import { encodePatch } from '../state/patchCode'
import { stressLoad, stressPatch } from './stressPatch'

const patch = stressPatch()
const { voices, effects, overlap } = stressLoad(patch)
const total = voices + effects
const round = (value: number) => value.toFixed(0)

const text = `Load test for the audio engine.

Forty-eight oscillators as siblings under one Ignite, covering all ten waveforms, all four filter
types and all four sequence lengths, plus five reverbs and five other effects, at ${patch.bpm} BPM on loop,
with a WARP on the Ignite running the whole cascade at half again its written speed.
Paste the code below into the PATCH CODE field.

Siblings rather than a deep cascade, which was the difference from the first version of this file.
A cascade sounds one level at a time, so twenty-four oscillators spread down five levels were a
handful playing at any instant — it measured 22 points out of ${MAX_LOAD}, which is one per cent, and had
been sitting there unnoticed since the ceiling was believed to be a hundred.

Everything a step can carry is in here, and not for completeness: each of them is load as well as
format. Rolls put four voices where one was, per-step velocity exercises the whole gain path rather
than the single value a patch of full-level notes tests, and the WARP's speed is the one control in
the instrument that multiplies the note rate of every oscillator below it at once. A load test that
only exercises the parameters that existed when it was written stops being a test of the engine and
becomes a test of its history.

The load, worked out from the note rate and the release rather than from the meter's estimate:

  voices  ${round(voices).padStart(7)}   48 oscillators, each holding about ${round(overlap)} at a time
  effects ${round(effects).padStart(7)}   five reverbs at their longest, and five cheaper ones
  total   ${round(total).padStart(7)}   against a layering threshold of ${round(MAX_LOAD * LAYER_THRESHOLD)} and a ceiling of ${MAX_LOAD}

So it is meant to sit past the point where the engine starts degrading and short of where it
breaks. That is the interesting place: a load test that always glitches tells you nothing, and one
that never does tells you less.

What to listen and look for:
  - crackling or dropouts, which would mean the audio thread is missing its window
  - the output clipping rather than being held by the limiter
  - the load meter going bright, and retriggered oscillators restarting rather than layering. That
    is the designed degradation, not a fault.
  - the whole thing running half again as fast from one control, which is the WARP on the far left.
    Unplug its cable and the same patch drops by about a third, which is the cheapest way to see
    what that one setting costs.

One thing the meter will not tell you: it reads well under half of what this costs. The estimate
caps how many voices an oscillator is assumed to be holding at four, and these hold about ${round(overlap)} — a
cap that keeps the dice honest and makes it blind to exactly this. Trust your ears over the number.

Generated by \`npm run stress\` (src/tools/stressPatch.ts) and checked on every test run by
src/state/stressPatch.test.ts, so neither the code nor the figures above it can drift.

${encodePatch(patch)}
`

writeFileSync('docs/stress-patch.txt', text)
console.log(`docs/stress-patch.txt — ${patch.nodes.length} nodes, ${round(total)} points`)
